#!/bin/bash
# Auto-generated by proton-drive-sync installer for headless keyring support
# This script starts gnome-keyring-daemon in headless environments

KEYRING_PASSWORD="{{KEYRING_PASSWORD}}"
KEYRING_ENV_FILE="{{KEYRING_ENV_FILE}}"

# Check if keyring is already running and accessible
if [ -f "$KEYRING_ENV_FILE" ]; then
	source "$KEYRING_ENV_FILE"
	if [ -n "$GNOME_KEYRING_PID" ] && kill -0 "$GNOME_KEYRING_PID" 2>/dev/null; then
		exit 0
	fi
fi

# Start dbus session if not running
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
	eval "$(dbus-launch --sh-syntax)"
fi

# Start gnome-keyring-daemon with login to unlock
eval "$(echo "$KEYRING_PASSWORD" | gnome-keyring-daemon --login)"
eval "$(gnome-keyring-daemon --start --components=secrets)"

# Create the "login" collection if it doesn't exist
# This is required on headless systems where the collection isn't auto-created
python3 -c "
import secretstorage
conn = secretstorage.dbus_init()
try:
    secretstorage.collection.create_collection(conn, 'Login', alias='default')
except secretstorage.exceptions.ItemExists:
    pass
" 2>/dev/null || true

# Export environment variables to file for other services
cat >"$KEYRING_ENV_FILE" <<EOF
DBUS_SESSION_BUS_ADDRESS="$DBUS_SESSION_BUS_ADDRESS"
GNOME_KEYRING_CONTROL="$GNOME_KEYRING_CONTROL"
GNOME_KEYRING_PID="$GNOME_KEYRING_PID"
EOF

chmod 600 "$KEYRING_ENV_FILE"
